# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


cards = [{ name: "AS", location: "deck", status: 1, cardFront: "&#127137", tablename: "Table1"},
  { name: "2S", location: "deck", status: 1, cardFront: "&#127138", tablename: "Table1"},
  { name: "3S", location: "deck", status: 1, cardFront: "&#127139", tablename: "Table1"},
  { name: "4S", location: "deck", status: 1, cardFront: "&#127140", tablename: "Table1"},
  { name: "5S", location: "deck", status: 1, cardFront: "&#127141", tablename: "Table1"},
  { name: "6S", location: "deck", status: 1, cardFront: "&#127142", tablename: "Table1"},
  { name: "7S", location: "deck", status: 1, cardFront: "&#127143", tablename: "Table1"},
  { name: "8S", location: "deck", status: 1, cardFront: "&#127144", tablename: "Table1"},
  { name: "9S", location: "deck", status: 1, cardFront: "&#127145", tablename: "Table1"},
  { name: "10S", location: "deck", status: 1, cardFront: "&#127146", tablename: "Table1"},
  { name: "JS", location: "deck", status: 1, cardFront: "&#127147", tablename: "Table1"},
  { name: "QS", location: "deck", status: 1, cardFront: "&#127149", tablename: "Table1"},
  { name: "KS", location: "deck", status: 1, cardFront: "&#127150", tablename: "Table1"},
  { name: "AH", location: "deck", status: 1, cardFront: "&#127153", tablename: "Table1"},
  { name: "2H", location: "deck", status: 1, cardFront: "&#127154", tablename: "Table1"},
  { name: "3H", location: "deck", status: 1, cardFront: "&#127155", tablename: "Table1"},
  { name: "4H", location: "deck", status: 1, cardFront: "&#127156", tablename: "Table1"},
  { name: "5H", location: "deck", status: 1, cardFront: "&#127157", tablename: "Table1"},
  { name: "6H", location: "deck", status: 1, cardFront: "&#127158", tablename: "Table1"},
  { name: "7H", location: "deck", status: 1, cardFront: "&#127159", tablename: "Table1"},
  { name: "8H", location: "deck", status: 1, cardFront: "&#127160", tablename: "Table1"},
  { name: "9H", location: "deck", status: 1, cardFront: "&#127161", tablename: "Table1"},
  { name: "10H", location: "deck", status: 1, cardFront: "&#127162", tablename: "Table1"},
  { name: "JH", location: "deck", status: 1, cardFront: "&#127163", tablename: "Table1"},
  { name: "QH", location: "deck", status: 1, cardFront: "&#127165", tablename: "Table1"},
  { name: "KH", location: "deck", status: 1, cardFront: "&#127166", tablename: "Table1"},
  { name: "AD", location: "deck", status: 1, cardFront: "&#127169", tablename: "Table1"},
  { name: "2D", location: "deck", status: 1, cardFront: "&#127170", tablename: "Table1"},
  { name: "3D", location: "deck", status: 1, cardFront: "&#127171", tablename: "Table1"},
  { name: "4D", location: "deck", status: 1, cardFront: "&#127172", tablename: "Table1"},
  { name: "5D", location: "deck", status: 1, cardFront: "&#127173", tablename: "Table1"},
  { name: "6D", location: "deck", status: 1, cardFront: "&#127174", tablename: "Table1"},
  { name: "7D", location: "deck", status: 1, cardFront: "&#127175", tablename: "Table1"},
  { name: "8D", location: "deck", status: 1, cardFront: "&#127176", tablename: "Table1"},
  { name: "9D", location: "deck", status: 1, cardFront: "&#127177", tablename: "Table1"},
  { name: "10D", location: "deck", status: 1, cardFront: "&#127178", tablename: "Table1"},
  { name: "JD", location: "deck", status: 1, cardFront: "&#127179", tablename: "Table1"},
  { name: "QD", location: "deck", status: 1, cardFront: "&#127181", tablename: "Table1"},
  { name: "KD", location: "deck", status: 1, cardFront: "&#127182", tablename: "Table1"},
  { name: "AC", location: "deck", status: 1, cardFront: "&#127185", tablename: "Table1"},
  { name: "2C", location: "deck", status: 1, cardFront: "&#127186", tablename: "Table1"},
  { name: "3C", location: "deck", status: 1, cardFront: "&#127187", tablename: "Table1"},
  { name: "4C", location: "deck", status: 1, cardFront: "&#127188", tablename: "Table1"},
  { name: "5C", location: "deck", status: 1, cardFront: "&#127189", tablename: "Table1"},
  { name: "6C", location: "deck", status: 1, cardFront: "&#127190", tablename: "Table1"},
  { name: "7C", location: "deck", status: 1, cardFront: "&#127191", tablename: "Table1"},
  { name: "8C", location: "deck", status: 1, cardFront: "&#127192", tablename: "Table1"},
  { name: "9C", location: "deck", status: 1, cardFront: "&#127193", tablename: "Table1"},
  { name: "10C", location: "deck", status: 1, cardFront: "&#127194", tablename: "Table1"},
  { name: "JC", location: "deck", status: 1, cardFront: "&#127195", tablename: "Table1"},
  { name: "QC", location: "deck", status: 1, cardFront: "&#127197", tablename: "Table1"},
  { name: "KC", location: "deck", status: 1, cardFront: "&#127198", tablename: "Table1"},
  { name: "RJ", location: "deck", status: 0, cardFront: "&#127167", tablename: "Table1"},
  { name: "BJ", location: "deck", status: 0, cardFront: "&#127183", tablename: "Table1"},
{ name: "AS", location: "deck", status: 1, cardFront: "&#127137", tablename: "Table2"},
  { name: "2S", location: "deck", status: 1, cardFront: "&#127138", tablename: "Table2"},
  { name: "3S", location: "deck", status: 1, cardFront: "&#127139", tablename: "Table2"},
  { name: "4S", location: "deck", status: 1, cardFront: "&#127140", tablename: "Table2"},
  { name: "5S", location: "deck", status: 1, cardFront: "&#127141", tablename: "Table2"},
  { name: "6S", location: "deck", status: 1, cardFront: "&#127142", tablename: "Table2"},
  { name: "7S", location: "deck", status: 1, cardFront: "&#127143", tablename: "Table2"},
  { name: "8S", location: "deck", status: 1, cardFront: "&#127144", tablename: "Table2"},
  { name: "9S", location: "deck", status: 1, cardFront: "&#127145", tablename: "Table2"},
  { name: "10S", location: "deck", status: 1, cardFront: "&#127146", tablename: "Table2"},
  { name: "JS", location: "deck", status: 1, cardFront: "&#127147", tablename: "Table2"},
  { name: "QS", location: "deck", status: 1, cardFront: "&#127149", tablename: "Table2"},
  { name: "KS", location: "deck", status: 1, cardFront: "&#127150", tablename: "Table2"},
  { name: "AH", location: "deck", status: 1, cardFront: "&#127153", tablename: "Table2"},
  { name: "2H", location: "deck", status: 1, cardFront: "&#127154", tablename: "Table2"},
  { name: "3H", location: "deck", status: 1, cardFront: "&#127155", tablename: "Table2"},
  { name: "4H", location: "deck", status: 1, cardFront: "&#127156", tablename: "Table2"},
  { name: "5H", location: "deck", status: 1, cardFront: "&#127157", tablename: "Table2"},
  { name: "6H", location: "deck", status: 1, cardFront: "&#127158", tablename: "Table2"},
  { name: "7H", location: "deck", status: 1, cardFront: "&#127159", tablename: "Table2"},
  { name: "8H", location: "deck", status: 1, cardFront: "&#127160", tablename: "Table2"},
  { name: "9H", location: "deck", status: 1, cardFront: "&#127161", tablename: "Table2"},
  { name: "10H", location: "deck", status: 1, cardFront: "&#127162", tablename: "Table2"},
  { name: "JH", location: "deck", status: 1, cardFront: "&#127163", tablename: "Table2"},
  { name: "QH", location: "deck", status: 1, cardFront: "&#127165", tablename: "Table2"},
  { name: "KH", location: "deck", status: 1, cardFront: "&#127166", tablename: "Table2"},
  { name: "AD", location: "deck", status: 1, cardFront: "&#127169", tablename: "Table2"},
  { name: "2D", location: "deck", status: 1, cardFront: "&#127170", tablename: "Table2"},
  { name: "3D", location: "deck", status: 1, cardFront: "&#127171", tablename: "Table2"},
  { name: "4D", location: "deck", status: 1, cardFront: "&#127172", tablename: "Table2"},
  { name: "5D", location: "deck", status: 1, cardFront: "&#127173", tablename: "Table2"},
  { name: "6D", location: "deck", status: 1, cardFront: "&#127174", tablename: "Table2"},
  { name: "7D", location: "deck", status: 1, cardFront: "&#127175", tablename: "Table2"},
  { name: "8D", location: "deck", status: 1, cardFront: "&#127176", tablename: "Table2"},
  { name: "9D", location: "deck", status: 1, cardFront: "&#127177", tablename: "Table2"},
  { name: "10D", location: "deck", status: 1, cardFront: "&#127178", tablename: "Table2"},
  { name: "JD", location: "deck", status: 1, cardFront: "&#127179", tablename: "Table2"},
  { name: "QD", location: "deck", status: 1, cardFront: "&#127181", tablename: "Table2"},
  { name: "KD", location: "deck", status: 1, cardFront: "&#127182", tablename: "Table2"},
  { name: "AC", location: "deck", status: 1, cardFront: "&#127185", tablename: "Table2"},
  { name: "2C", location: "deck", status: 1, cardFront: "&#127186", tablename: "Table2"},
  { name: "3C", location: "deck", status: 1, cardFront: "&#127187", tablename: "Table2"},
  { name: "4C", location: "deck", status: 1, cardFront: "&#127188", tablename: "Table2"},
  { name: "5C", location: "deck", status: 1, cardFront: "&#127189", tablename: "Table2"},
  { name: "6C", location: "deck", status: 1, cardFront: "&#127190", tablename: "Table2"},
  { name: "7C", location: "deck", status: 1, cardFront: "&#127191", tablename: "Table2"},
  { name: "8C", location: "deck", status: 1, cardFront: "&#127192", tablename: "Table2"},
  { name: "9C", location: "deck", status: 1, cardFront: "&#127193", tablename: "Table2"},
  { name: "10C", location: "deck", status: 1, cardFront: "&#127194", tablename: "Table2"},
  { name: "JC", location: "deck", status: 1, cardFront: "&#127195", tablename: "Table2"},
  { name: "QC", location: "deck", status: 1, cardFront: "&#127197", tablename: "Table2"},
  { name: "KC", location: "deck", status: 1, cardFront: "&#127198", tablename: "Table2"},
  { name: "RJ", location: "deck", status: 0, cardFront: "&#127167", tablename: "Table2"},
  { name: "BJ", location: "deck", status: 0, cardFront: "&#127183", tablename: "Table2"}
]
cards.each do |card|
  Card.create!(card)
end

tables = [{tablename: "Table1"},{tablename: "Table2"}]

tables.each do |table|
  Table.create!(table)
end